### ISSUE TITLE
Error in check_download_ptf_group

### ISSUE THREAD

**Issue by JaKo8103** [IBM/ansible-for-i#118]
Hi,
I am having trouble entering data into repo.sqlite3
Mianowice does not add information to the download_status table. Therefore, I download the same PTF group every time.
I have such a mistake:
2021-11-15T13:21:03.5135276Z   File "/tmp/ansible_ibm.power_ibmi.ibmi_download_fix_payload_2wo3wjbv/ansible_ibm.power_ibmi.ibmi_download_fix_payload.zip/ansible_collections/ibm/power_ibmi/plugins/modules/ibmi_download_fix.py", line 577, in <module>
2021-11-15T13:21:03.5136582Z   File "/tmp/ansible_ibm.power_ibmi.ibmi_download_fix_payload_2wo3wjbv/ansible_ibm.power_ibmi.ibmi_download_fix_payload.zip/ansible_collections/ibm/power_ibmi/plugins/modules/ibmi_download_fix.py", line 460, in main
2021-11-15T13:21:03.5138622Z AttributeError: 'NoneType' object has no attribute 'group'
2021-11-15T13:21:03.5139635Z Exception ignored in: <function IBMiModule.__del__ at 0x70000000076a9d0>
2021-11-15T13:21:03.5140605Z Traceback (most recent call last):
2021-11-15T13:21:03.5141516Z   File "/tmp/ansible_ibm.power_ibmi.ibmi_download_fix_payload_2wo3wjbv/ansible_ibm.power_ibmi.ibmi_download_fix_payload.zip/ansible_collections/ibm/power_ibmi/plugins/module_utils/ibmi/ibmi_module.py", line 200, in __del__
2021-11-15T13:21:03.5142921Z   File "/tmp/ansible_ibm.power_ibmi.ibmi_download_fix_payload_2wo3wjbv/ansible_ibm.power_ibmi.ibmi_download_fix_payload.zip/ansible_collections/ibm/power_ibmi/plugins/module_utils/ibmi/ibmi_module.py", line 229, in itoolkit_close_connection
2021-11-15T13:21:03.5144305Z   File "/tmp/ansible_ibm.power_ibmi.ibmi_download_fix_payload_2wo3wjbv/ansible_ibm.power_ibmi.ibmi_download_fix_payload.zip/ansible_collections/ibm/power_ibmi/plugins/module_utils/ibmi/ibmi_module.py", line 225, in close_db_connection
2021-11-15T13:21:03.5146316Z Exception: Failed to close connect from database: ibm_db_dbi::Error: Exception('Supplied connection object Parameter is invalid')

**Comment by JaKo8103** [comment]
problem of python.
Resolved :)
