### ISSUE TITLE
variable usage

### ISSUE THREAD

**Issue by Ludovic-Menard** [IBM/ansible-for-i#129]
Hello,
I am trying to use variable on my playbook but I receive this message below
My code without variable works fine:
---
- hosts: ibmi
  gather_facts: false
  collections:
    - ibm.power_ibmi

  tasks:

    - name: create user profile ludo
      ibmi_user_and_group:
        operation: 'create'
        user: 'ludo'
        user_class: '*SECOFR'
      register: user_result
    - debug:
       var: user_result

with variable : 
---
- hosts: ibmi
  gather_facts: false
  collections:
    - ibm.power_ibmi

  vars:
          user_profile: ludo
  tasks:

    - name: create user profile {{user_profile}}
      ibmi_user_and_group:
        operation: 'create'
        user: '{{user_profile}}'
        user_class: '*SECOFR'
      register: user_result
    - debug:
       var: user_result

The full traceback is:
Traceback (most recent call last):
  File "/home/ansible/.ansible/tmp/ansible-tmp-1650359666.1590996-1729627-188061679756571/AnsiballZ_ibmi_user_and_group.py", line 102, in <module>
    _ansiballz_main()
  File "/home/ansible/.ansible/tmp/ansible-tmp-1650359666.1590996-1729627-188061679756571/AnsiballZ_ibmi_user_and_group.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/ansible/.ansible/tmp/ansible-tmp-1650359666.1590996-1729627-188061679756571/AnsiballZ_ibmi_user_and_group.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.ibm.power_ibmi.plugins.modules.ibmi_user_and_group', init_globals=None, run_name='__main__', alter_sys=True)
  File "/QOpensys/pkgs/lib/python2.7/runpy.py", line 182, in run_module
    mod_name, loader, code, fname = _get_module_details(mod_name)
  File "/QOpensys/pkgs/lib/python2.7/runpy.py", line 119, in _get_module_details
    code = loader.get_code(mod_name)
  File "/tmp/ansible_ibmi_user_and_group_payload_x0X0Dd/ansible_ibmi_user_and_group_payload.zip/ansible_collections/ibm/power_ibmi/plugins/modules/ibmi_user_and_group.py", line 308
    msg=f"{item} must be only value for parameter special_authority")
                                                                   ^
SyntaxError: invalid syntax
fatal: [10.3.60.128]: FAILED! => {
    "changed": false,
    "module_stderr": "Shared connection to 10.3.60.128 closed.\r\n",
    "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/ansible/.ansible/tmp/ansible-tmp-1650359666.1590996-1729627-188061679756571/AnsiballZ_ibmi_user_and_group.py\", line 102, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/ansible/.ansible/tmp/ansible-tmp-1650359666.1590996-1729627-188061679756571/AnsiballZ_ibmi_user_and_group.py\", line 94, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/ansible/.ansible/tmp/ansible-tmp-1650359666.1590996-1729627-188061679756571/AnsiballZ_ibmi_user_and_group.py\", line 40, in invoke_module\r\n    runpy.run_module(mod_name='ansible_collections.ibm.power_ibmi.plugins.modules.ibmi_user_and_group', init_globals=None, run_name='__main__', alter_sys=True)\r\n  File \"/QOpensys/pkgs/lib/python2.7/runpy.py\", line 182, in run_module\r\n    mod_name, loader, code, fname = _get_module_details(mod_name)\r\n  File \"/QOpensys/pkgs/lib/python2.7/runpy.py\", line 119, in _get_module_details\r\n    code = loader.get_code(mod_name)\r\n  File \"/tmp/ansible_ibmi_user_and_group_payload_x0X0Dd/ansible_ibmi_user_and_group_payload.zip/ansible_collections/ibm/power_ibmi/plugins/modules/ibmi_user_and_group.py\", line 308\r\n    msg=f\"{item} must be only value for parameter special_authority\")\r\n                                                                   ^\r\nSyntaxError: invalid syntax\r\n",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

Thanks for your help
Ludo

**Comment by Ludovic-Menard** [comment]
It was an error
