### ISSUE TITLE
Errno 14] curl#6 - "Could not resolve host: public.dhe.ibm.com" Trying other mirror.

### ISSUE THREAD

**Issue by mad5bo** [IBM/ansible-for-i#74]
Hi, the main goal is to install Ansible controller on IBM i, the IBM i VM is provisioned off-premises at IBM Cloud and has an External IP, so can get access to the Internet.

1. The RPM setup did well, running  bootstrap.sql

![image](https://user-images.githubusercontent.com/68882369/107832565-7cf28c80-6d6f-11eb-886e-56bcc89d383b.png)

2. Using ACS the connections by SSH to the VM did well. 

3. Then trying to install any package this message is displayed 
ftp://public.dhe.ibm.com/software/ibmi/products/pase/rpms/repo/repodata/repomd.xml: [Errno 14] curl#6 - "Could not resolve host: public.dhe.ibm.com"
Trying other mirror.
Setting up Upgrade Process
Resolving Dependencies
--> Running transaction check
---> Package yum.noarch 0:3.4.3-14 will be updated
---> Package yum.noarch 0:3.4.3-18 will be an update
--> Processing Dependency: python2-iniparse for package: yum-3.4.3-18.noarch
--> Running transaction check
---> Package python2-iniparse.noarch 0:0.4-2 will be installed
Error: Rpmdb changed underneath us
Traceback (most recent call last):
  File "/QOpenSys/pkgs/bin/yum", line 29, in <module>
    yummain.user_main(sys.argv[1:], exit_code=True)
  File "/QOpenSys/pkgs/share/yum-cli/yummain.py", line 288, in user_main
    errcode = main(args)
  File "/QOpenSys/pkgs/share/yum-cli/yummain.py", line 203, in main
    if base._depsolving_failed:
AttributeError: 'YumBaseCli' object has no attribute '_depsolving_failed'

4. Even if you try to display the information only
![image](https://user-images.githubusercontent.com/68882369/107832821-36e9f880-6d70-11eb-9d7c-7547fa7ed89e.png)

5. Doing this test is OK
![image](https://user-images.githubusercontent.com/68882369/107832892-639e1000-6d70-11eb-99c6-70e2ee9b1249.png)

6. DNS looks as follows
![image](https://user-images.githubusercontent.com/68882369/107832922-757fb300-6d70-11eb-8b03-2760dddd622d.png)
![image](https://user-images.githubusercontent.com/68882369/107832932-7c0e2a80-6d70-11eb-8ad3-00dc27100260.png)

Is there any other consideration for IBM i off-premises?

Thanks in advance!

**Comment by mad5bo** [comment]
I added the IP of the repository at DNS
